### ISSUE TITLE
What are the parts? How do they interact?

### ISSUE THREAD

**Issue by Derevi** [Derevi/breakfast-club-as1#2]

**Comment by Nina1234y** [comment]
[as1.pdf](https://github.com/Derevi/breakfast-club-as1/files/7230540/as1.pdf)

**Comment by Derevi** [comment]
I had a chance to review your write up Nina, here are some notes, let me know if i missed anything in your report, which negates any point.:
- I dont think you need to  reference specific .c classes since the assignment looks at a higher level design view.
From the assignment handout: 
 _"Your  reports should  present  the  conceptual  structure  of  the  software  system  rather  than  discuss  the  details  of  its implementation. "_
- Im still not exactly sure what the parts/subsystems are, can you explicitly list them 1 by 1 and what they do with each other in general. Its seems like its embedded in the procedural flow of the report, but its not super clear to me and its difficult to decipher at a high level, like im not sure what constitutes a highlevel architectural component, and what is just a simple process. Using the linux kernel as an example the parts of a linux kernel are, file systems, process manager, network manager, device driver, network.
- Its a little hard for me to understand at a high level what is going on and how stuff is interacting. Example: The postmaster seems like an important architectural component, and i understand what it does procedurally, but its not clear at a high level, what its actual purpose is, what is it managing, why is it needed? 
...My (rough) understanding from my use of postgres is that the postmaster is just the daemon that clients connect to that takes in commands and passes it to postgres, so essentially postmaster itself is the server. So it serves as the communication link between the client and the database. (i can find a citation for this if you need). 
**EDIT**: just checked the current documentation it seems postmaster is deprecated, its just an alias to postgres now.

..let me know if you need some help, you can ping me on discord, continue this thread, or assign an issue to me.

**Comment by Nina1234y** [comment]
[as1_v2.pdf](https://github.com/Derevi/breakfast-club-as1/files/7247032/as1_v2.pdf)

Thanks for the input. I rewrote the whole think and focused of client-server/ pipeline&filter / implicit invocation / repository styles.

All the parts in red mean that I'm not sure whether it should be included or not.
I couldn't find much about the storage architecture. If anyone can find something about storage architecture and/ or provide constructive criticism, that would help.

**Comment by Derevi** [comment]
The Main Query flow, you put that it is implicit invocation, event based, but the way you described it looks more like, pipes and filters within layers where your layers would be the stages you mentioned and tcop would be like a middleman. 
If its eventbased does that mean the Query is the event and the central hub is the postgres server? I somewhat understand how it could fit, but its not super clear, it seems like it would be more closer to publisher subscriber?

**EDIT:** I for got to mention that there are event based architectural stuff (see ch.39 of the official postgres doc) but Im not sure if this is too low level, in any case I would need to know what the events are, the components that listen to the events, and what is the eventbus.
...
Extra Info on Eventbased architecture that may help (or not, skip if you want), i used this architecture recently so its still fresh:
Event based architecture requires that, everyone passes an event (usually a message) to some central hub (usually called an eventbus) and all that central hub does is broadcasts these events to everyone. Based on events received, that person can do something with the information or not.
Ex. like when youre on a zoom lecture... when you type something in the chat to everyone, your message is broadcasted to all the people in the zoom lecture so they are like the listeners who may or may do something based on your message, and the chat box it self would be the eventbus. The eventbus should be nothing more then just a component to broadcast to everyone like a megaphone.
