### ISSUE TITLE
What are the implications for division of responsibilities among participating developers?

### ISSUE THREAD

**Issue by Derevi** [Derevi/breakfast-club-as1#6]

**Comment by t1shfiq** [comment]
[Division of Responsibilities.pdf](https://github.com/Derevi/breakfast-club-as1/files/7257394/Division.of.Responsibilities.pdf)

Will fix the citations later. Looking to see what can be added.

**Comment by Derevi** [comment]
Reviewed it and my thoughts:
- overall i understand whats going on, but its because i have background knowledge on opensource stuff, you may want add more details to portions, specifically you have a single implication, you can add a few more.
-The contributions from volunteers stated in your 3rd paragraph, do the still have to be reviewed and approved by the core team? If so you may want to mention this, and it can be an implication as well, volunteers can request features, and submit issues, and even fix issues, but if the core team doesnt approve than it doesnt matter.
-Disadvantages can be listed. I dont have sources for this its just my exp with open source. If there is a bug, and the core team doesnt care about it, it wont get fixed. But a closed source software are more inclined to fix things for paying customers.
-Additionally since it is so widely used, in industry, if there is a bug a feature that effects some business, they can actually fix it themselves overall improving postgres. Compared to closed source where you have to wait for them to fix it. As an example, Huawei is one of the biggest contributors to the linux kernel simply because the need to add features to official linux kernel to support their hardware. A lot of popular opensource stuff is actually backed by large companies.
- You can maybe draw up some architectural diagram of the stake holders, via use case or show the hierarchy, a rough example:
![image](https://user-images.githubusercontent.com/34952812/135701477-ccc9e174-a4d3-4611-8557-7214a72db2e1.png)
It would be nice to so how responsiblities are divided by some diagram, even if it is really simple.
- In the first paragraph you stated that postgres is opensource, but not why it matters for your section. Maybe add something there in the first paragraph that specifies that because it is opensource, it will inherit alot of the same divisions of responsibility as any large opensource project


.....your gonna have to double fact check and get citations maybe, but its kind of general experience of open source.
